import {del} from './delete'
export {del as delete}
export {publish} from './publish'
export {patch} from './patch'
export {commit} from './commit'
export {discardChanges} from './discardChanges'
export {unpublish} from './unpublish'
export {duplicate} from './duplicate'
export {restore} from './restore'
