/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/extractFromSanitySchema-blog.test.js TAP blog schema matches snapshot > undefined 1`] = `
{ types:
   [ { kind: 'Type',
       name: 'Image',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'asset',
            type: 'SanityImageAsset',
            description: undefined,
            isReference: true },
          { fieldName: 'hotspot', type: 'SanityImageHotspot' },
          { fieldName: 'crop', type: 'SanityImageCrop' } ],
       originalName: 'image' },
     { kind: 'Type',
       name: 'File',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'asset',
            type: 'SanityFileAsset',
            description: undefined,
            isReference: true } ],
       originalName: 'file' },
     { kind: 'Type',
       name: 'Block',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'children',
            children: { type: 'Span' },
            description: undefined,
            kind: 'List' },
          { fieldName: 'style', type: 'String', description: undefined },
          { fieldName: 'list', type: 'String', description: undefined } ],
       originalName: 'block' },
     { kind: 'Type',
       name: 'Span',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'marks',
            children: { type: 'String' },
            description: undefined,
            kind: 'List' },
          { fieldName: 'text', type: 'String', description: undefined } ],
       originalName: 'span' },
     { kind: 'Type',
       name: 'Post',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' },
          { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: 'title', type: 'String', description: undefined },
          { fieldName: 'slug', type: 'Slug' },
          { fieldName: 'author',
            type: 'Author',
            description: undefined,
            isReference: true },
          { fieldName: 'testCircularAuthor',
            type: 'Author',
            description: undefined,
            isReference: true },
          { fieldName: 'mainImage', type: 'Image' },
          { fieldName: 'categories',
            children:
             { type: 'Category', description: undefined, isReference: true },
            description: undefined,
            kind: 'List' },
          { fieldName: 'publishedAt',
            type: 'Datetime',
            description: undefined },
          { fieldName: 'bodyRaw',
            type: 'JSON',
            description: undefined,
            originalName: 'body',
            isRawAlias: true } ],
       interfaces: [ 'Document' ],
       originalName: 'post' },
     { kind: 'Type',
       name: 'Author',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' },
          { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: 'name', type: 'String', description: undefined },
          { fieldName: 'slug', type: 'Slug' },
          { fieldName: 'image', type: 'Image' },
          { fieldName: 'bioRaw',
            children: { type: 'Block' },
            description: undefined,
            kind: 'List',
            originalName: 'bio',
            type: 'JSON',
            isRawAlias: true } ],
       interfaces: [ 'Document' ],
       originalName: 'author' },
     { kind: 'Type',
       name: 'Category',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' },
          { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: 'title', type: 'String', description: undefined },
          { fieldName: 'description',
            type: 'Text',
            description: undefined } ],
       interfaces: [ 'Document' ],
       originalName: 'category' },
     { children: { type: 'BlockOrImage', references: undefined },
       description: undefined,
       kind: 'List',
       name: 'BlockContent',
       originalName: 'blockContent' },
     { kind: 'Type',
       name: 'Slug',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'current', type: 'String', description: undefined } ],
       originalName: 'slug' },
     { kind: 'Type',
       name: 'Geopoint',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'lat', type: 'Float', description: undefined },
          { fieldName: 'lng', type: 'Float', description: undefined },
          { fieldName: 'alt', type: 'Float', description: undefined } ],
       originalName: 'geopoint' },
     { kind: 'Type',
       name: 'SanityImageAsset',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' },
          { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: 'originalFilename',
            type: 'String',
            description: undefined },
          { fieldName: 'label', type: 'String', description: undefined },
          { fieldName: 'sha1hash', type: 'String', description: undefined },
          { fieldName: 'extension',
            type: 'String',
            description: undefined },
          { fieldName: 'mimeType', type: 'String', description: undefined },
          { fieldName: 'size', type: 'Float', description: undefined },
          { fieldName: 'assetId', type: 'String', description: undefined },
          { fieldName: 'path', type: 'String', description: undefined },
          { fieldName: 'url', type: 'String', description: undefined },
          { fieldName: 'metadata', type: 'SanityImageMetadata' } ],
       interfaces: [ 'Document' ],
       originalName: 'sanity.imageAsset' },
     { kind: 'Type',
       name: 'SanityFileAsset',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' },
          { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: 'originalFilename',
            type: 'String',
            description: undefined },
          { fieldName: 'label', type: 'String', description: undefined },
          { fieldName: 'sha1hash', type: 'String', description: undefined },
          { fieldName: 'extension',
            type: 'String',
            description: undefined },
          { fieldName: 'mimeType', type: 'String', description: undefined },
          { fieldName: 'size', type: 'Float', description: undefined },
          { fieldName: 'assetId', type: 'String', description: undefined },
          { fieldName: 'path', type: 'String', description: undefined },
          { fieldName: 'url', type: 'String', description: undefined } ],
       interfaces: [ 'Document' ],
       originalName: 'sanity.fileAsset' },
     { kind: 'Type',
       name: 'SanityImageCrop',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'top', type: 'Float', description: undefined },
          { fieldName: 'bottom', type: 'Float', description: undefined },
          { fieldName: 'left', type: 'Float', description: undefined },
          { fieldName: 'right', type: 'Float', description: undefined } ],
       originalName: 'sanity.imageCrop' },
     { kind: 'Type',
       name: 'SanityImageHotspot',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'x', type: 'Float', description: undefined },
          { fieldName: 'y', type: 'Float', description: undefined },
          { fieldName: 'height', type: 'Float', description: undefined },
          { fieldName: 'width', type: 'Float', description: undefined } ],
       originalName: 'sanity.imageHotspot' },
     { kind: 'Type',
       name: 'SanityImageMetadata',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'location', type: 'Geopoint' },
          { fieldName: 'dimensions', type: 'SanityImageDimensions' },
          { fieldName: 'palette', type: 'SanityImagePalette' },
          { fieldName: 'lqip', type: 'String', description: undefined } ],
       originalName: 'sanity.imageMetadata' },
     { kind: 'Type',
       name: 'SanityImageDimensions',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'height', type: 'Float', description: undefined },
          { fieldName: 'width', type: 'Float', description: undefined },
          { fieldName: 'aspectRatio',
            type: 'Float',
            description: undefined } ],
       originalName: 'sanity.imageDimensions' },
     { kind: 'Type',
       name: 'SanityImagePalette',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'darkMuted', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'lightVibrant', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'darkVibrant', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'vibrant', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'dominant', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'lightMuted', type: 'SanityImagePaletteSwatch' },
          { fieldName: 'muted', type: 'SanityImagePaletteSwatch' } ],
       originalName: 'sanity.imagePalette' },
     { kind: 'Type',
       name: 'SanityImagePaletteSwatch',
       type: 'Object',
       description: undefined,
       fields:
        [ { fieldName: '_key', type: 'String', description: undefined },
          { fieldName: '_type', type: 'String', description: undefined },
          { fieldName: 'background',
            type: 'String',
            description: undefined },
          { fieldName: 'foreground',
            type: 'String',
            description: undefined },
          { fieldName: 'population',
            type: 'Float',
            description: undefined },
          { fieldName: 'title', type: 'String', description: undefined } ],
       originalName: 'sanity.imagePaletteSwatch' },
     { kind: 'Union',
       name: 'BlockOrImage',
       types: [ 'Block', 'Image' ],
       interfaces: undefined } ],
  interfaces:
   [ { kind: 'Interface',
       name: 'Document',
       description: 'A Sanity document',
       fields:
        [ { fieldName: '_id',
            type: 'ID',
            isNullable: false,
            description: 'Document ID' },
          { fieldName: '_type',
            type: 'String',
            isNullable: false,
            description: 'Document type' },
          { fieldName: '_createdAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was created' },
          { fieldName: '_updatedAt',
            type: 'Datetime',
            isNullable: false,
            description: 'Date the document was last modified' },
          { fieldName: '_rev',
            type: 'String',
            isNullable: false,
            description: 'Current document revision' } ] } ] }
`
